version: '3'

services:
  tika:
    image: apache/tika:2.9.1.0
    ports:
      - "9998:9998"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:9998/tika"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    environment:
      - JAVA_OPTS=-Xmx2g  # Allocate 2GB of memory to Tika 